//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anotame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nota()
        {
            this.NotaPrenda = new HashSet<NotaPrenda>();
        }
    
        public int id { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public System.DateTime FechaRecibido { get; set; }
        public int idEmpresa { get; set; }
        public int Folio { get; set; }
        public int idClientes { get; set; }
        public decimal Total { get; set; }
        public int idEmpleado { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaPrenda> NotaPrenda { get; set; }
    }
}
