//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anotame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaPrenda
    {
        public int id { get; set; }
        public Nullable<int> idNota { get; set; }
        public int idPrenda { get; set; }
        public string Descripcion { get; set; }
        public int CantidadPrendas { get; set; }
    
        public virtual Nota Nota { get; set; }
        public virtual Prenda Prenda { get; set; }
    }
}
