//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anotame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prenda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prenda()
        {
            this.NotaPrenda = new HashSet<NotaPrenda>();
        }
    
        public int id { get; set; }
        public int idTipoPrenda { get; set; }
        public int idArreglo { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Arreglo Arreglo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaPrenda> NotaPrenda { get; set; }
        public virtual TipoPrenda TipoPrenda { get; set; }
    }
}
